core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quiz.urls")),
]

quiz/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "quiz"
urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("create/", views.create,name="create"),
    path("create/<uuid:pk>", views.create_quiz,name="create-quiz"),
    path("question/", views.new_question, name='new-question'),
    path("detail/<uuid:pk>/", views.quiz_detail,  name="quiz_detail"),
    path("list/", views.list_quiz, name='list-quiz'),
    path("explore/",views.explore, name='explore'),
    path("start/<uuid:pk>/", views.start_quiz, name="start-quiz"),
    path("edit/<uuid:pk>/", views.edit_quiz, name="edit-quiz"),
    path("edit/<int:id>/", views.edit_question, name="edit-question"),
    path("edit/quiz/<uuid:pk>/", views.edit_quiz_form, name='edit_quiz_form'),
    path("results/", views.results, name='results'),
    path("contact/", views.Contact.as_view(), name='contact'),
    path("about/", views.About.as_view(), name='about'),
    # Authentication URLs
    path(
        "login/",
        auth_views.LoginView.as_view(redirect_authenticated_user=True),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path("signup/", views.SignUp.as_view(), name="signup"),
]

quiz/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid


class User(AbstractUser):
    pass

class Subject(models.Model):
    name = models.CharField(max_length=200)
    sub_code = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name",)
        verbose_name = "Subject"
        verbose_name_plural = "Subjects"


class Quiz(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200 ,blank=True, null=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    authored_on = models.DateTimeField(auto_now=True)
    authored_by = models.ForeignKey(User, on_delete=models.CASCADE)
    is_private = models.BooleanField(default=False)

    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ("-authored_on",)
        verbose_name = "Quiz"
        verbose_name_plural = "Quizzes"


class Question(models.Model):
    name = models.CharField(max_length=800)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Question"
        verbose_name_plural = "Questions"


class Option(models.Model):
    name = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Option"
        verbose_name_plural = "Options"

class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    by = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.PositiveIntegerField()
    created_at = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = 'Result'
        verbose_name_plural = 'Results'
    

quiz/forms.py
from django import forms
from .models import User, Quiz
from django.contrib.auth.forms import UserCreationForm


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "username",
            "password1",
            "password2",
        )

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in ["username", "password1", "password2"]:
            self.fields[field].help_text = None
            self.fields['first_name'].label = 'Name'
            self.fields['first_name'].required = True

class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        exclude = ['authored_by',]
    def __init__(self, *args, **kwargs):
        super(QuizForm, self).__init__(*args, **kwargs)
        self.fields['title'].label = ''
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'special special_big', 'placeholder':'Quiz Title'}))


class QuestionForm(forms.Form):
    quiz = forms.UUIDField(widget=forms.HiddenInput())
    question = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'special', 'placeholder':'Question'}))
    option_1 = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'special special_small', 'placeholder':'Option A'}))
    option_2 = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'special special_small', 'placeholder':'Option B'}))
    option_3 = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'special special_small', 'placeholder':'Option C'}))
    correct_answer = forms.ChoiceField(choices=[(1, 'A'), (2, 'B'), (3, 'C')], widget=forms.RadioSelect(attrs={'class':'radio-inline', 'required':True}))

    

quiz/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, CreateView
from django.contrib.auth import get_user_model
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import UserForm, QuizForm, QuestionForm
from .models import User, Subject, Quiz, Question, Option, Result
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

class Home(LoginRequiredMixin, TemplateView):
    template_name = "quiz/index.html"

class Contact(TemplateView):
    template_name = "quiz/contact.html"

class About(TemplateView):
    template_name = "quiz/aboutus.html"


class SignUp(CreateView):
    model = get_user_model
    form_class = UserForm
    success_url = "/"
    template_name = "registration/signup.html"

    def form_valid(self, form):
        user = form.save(commit=False)
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password1"]
        new_user = authenticate(self.request, username=username, password=password)
        user.save()
        if new_user is not None:
            login(self.request, user=new_user)

        return super().form_valid(form)

@login_required()
def create(request):
    subjects = Subject.objects.all().values_list('name')
    form = QuizForm()
    question_form= None
    disabled = False
    if request.method == "POST":
        form = QuizForm(request.POST)
        if form.is_valid():
            quiz = form.save(commit=False)
            quiz.authored_by = request.user
            quiz.save()
            return redirect(reverse('quiz:create-quiz', kwargs={'pk':quiz.id}))
    return render(request, "quiz/create.html", {'subjects':subjects, 'disabled':disabled, 'form':form, 'question_form':question_form})

@login_required()
def create_quiz(request, pk):
    form = QuestionForm(initial={'quiz':pk})
    return render(request, 'quiz/create_questions.html', {'form':form})

def new_question(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            question = Question.objects.create(quiz_id=cd['quiz'], name=cd['question'])
            for i in [1,2,3]:
                option = Option.objects.create(name=cd[f'option_{i}'], is_correct=(i==int(cd['correct_answer'])), question=question)

            form = QuestionForm(initial={'quiz':cd['quiz']})
    
    return render(request, 'quiz/question.html', {'form':form})

@login_required()
def quiz_detail(request, pk):
    quiz = Quiz.objects.get(id=pk)
    return render(request, 'quiz/detail.html', {'quiz':quiz})

@login_required()
def list_quiz(request):
    quiz_qs = Quiz.objects.filter(authored_by=request.user)
    return render(request, 'quiz/quiz_list.html', {'quiz_qs':quiz_qs})

@login_required()
def explore(request):
    quiz_qs = Quiz.objects.exclude(authored_by=request.user).exclude(is_private=True)
    return render(request, 'quiz/quiz_list.html', {'quiz_qs':quiz_qs, 'start':True})

@login_required()
def start_quiz(request, pk):
    quiz = Quiz.objects.get(id=pk)
    count = 0
    correct = []
    given = False
    if request.method == 'POST':
        questions = quiz.question_set.all()
        for question in questions:
            option = question.option_set.all().get(is_correct=True)
            if option.id == int(request.POST.get(f'option_{question.id}')):
                count+=1
                correct.append(question)
        result = Result.objects.create(by=request.user, quiz=quiz, score=count)
        given = True
    return render(request, "quiz/start.html", {'quiz':quiz, 'score':count, 'given':given, 'correct':correct})

@login_required()
def edit_quiz(request, pk):
    quiz = Quiz.objects.get(id=pk)

    return render(request, 'quiz/edit.html', {'quiz':quiz})


@login_required()
def edit_question(request, id):
    question = Question.objects.get(id=id)
    options = question.option_set.all()
    correct = [all(i) for i in (options.values_list('is_correct'))].index(True) +1
    form = QuestionForm(initial={'quiz': question.quiz, 'question':question.name, 'option_1': options[0].name, 'option_2':options[1].name, 'option_3':options[2].name,'correct_answer':correct})
    if request.method == "POST":
        form = QuestionForm(request.POST)
        print(form.errors)
        if form.is_valid():
            cd = form.cleaned_data
            question.name = cd['question']
            question.save()
            for i,option in enumerate(options, 1):
                option.name, option.is_correct =cd[f'option_{i}'],False
                if int(cd['correct_answer']) == i: option.is_correct=True
                option.save()
            return render(request, 'quiz/return_question.html', {'question':question})
   
    return render(request, "quiz/question_form.html", {'form':form, 'id':id})

@login_required()
def edit_quiz_form(request, pk):
    quiz = Quiz.objects.get(id=pk)
    form = QuizForm(instance=quiz)
    saved = False
    if request.method == "POST":
        form = QuizForm(request.POST, instance=quiz)
        form.save()
        saved = True
    return render(request, 'quiz/quiz_info_return.html', {'form':form,'quiz':quiz, 'saved':saved})

@login_required()
def results(request):
    results_qs = Result.objects.all().filter(by=request.user).order_by('quiz')
    return render(request, 'quiz/results.html', {'results': results_qs})

quiz/templates/quiz/aboutus.html
{% extends 'base.html' %}
{% block title %}
About Us
{% endblock title %}
{% block content %}
<div class="container">
    <div class="display-2">About Us</div>
    <div class="fs-4">

        We are a team of passionate individuals who believe that learning should be fun and accessible to everyone. That's why
        we created this Quiz Application - to bring the excitement of quizzes to your fingertips.
    
    With our app, you can test your knowledge on a wide range of topics, from history and science to pop culture and
    entertainment. Our quizzes are designed to be engaging, challenging, and thought-provoking, making sure that you learn
    something new every time you play.
    
    We are constantly updating our database with new quizzes and questions, ensuring that there is always something new for
    you to discover. Our user-friendly interface makes it easy for you to navigate and find the quizzes that interest you
    the most.
    
    Our mission is to provide a platform for anyone to learn, explore and challenge themselves in a fun and interactive way.
    Whether you're a student looking to brush up on your knowledge, or simply someone looking for a fun way to pass the
    time, our Quiz Application has something for everyone.
    
    So, why not challenge yourself and see how much you know? Download our Quiz Application today and start exploring the
    world of quizzes!
    
    Thank you for choosing our Quiz Application. We can't wait for you to join the millions of users who have already
    discovered the joy of learning with us.
</div>
</div>
{% endblock content %}

quiz/templates/quiz/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Contact Us
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="display-2">Contact Us</div>
        <div class="fs-4">

            We are always here to help you with any questions or concerns you may have about our Quiz Application. Whether you need
            assistance with using the app, have a suggestion for a new quiz, or simply want to share your thoughts, we'd love to
        hear from you.
        <div class="gmail-link mt-3">
            <a href="mailto:contactvivekhere@gmail.com" class="text-decoration-none">

                <img src="{% static 'images/gmail-button.png' %}" alt="" width="300px">
            </a>
        </div>
        <div class="whatsapp-link mt-3">
            <a href="https://wa.me/919453912043">
                <img src="{% static 'images/whatsapp-button.png' %}" alt=""  width="300px">
            </a>
        </div>
    </div>
</div>
{% endblock content %}

quiz/templates/quiz/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Create a new Quiz - Quizta
{% endblock title %}
{% block content %}
<div class="bg-white d-flex justify-content-center" style="height:100vh">

    <form method="post" class="form_container mt-5" style=" border: none;">
        {% csrf_token %}
        
        {{form|crispy}}
        
        <input type="submit" class="btn btn-success" value="Create">    
        
    </div>
</form>
<input type="text" placeholder="Title" class="special">
</div>
{% endblock content %}

quiz/templates/quiz/create_questions.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Input Question
{% endblock title %}
{% block content %}
<div class="bg-white d-flex flex-column align-items-center" style="height:100vh">

    <form method="post" class="mt-5">
        {% csrf_token %}
        <div id="question-container">
            {{form|crispy}}
            
        </div>
        <button type="submit" hx-post="{% url 'quiz:new-question' %}" hx-swap="innerHTML" hx-target="#question-container" class="btn btn-success"> Create </button>
    </form>
    <a href="{% url 'quiz:quiz_detail' form.quiz.value %}" class=" text-decoration-none text-white"><button class="btn btn-success" style="width:300px;">Exit to Detail </button></a>

    </div>
        {% endblock content %}

quiz/templates/quiz/detail.html
{% extends 'base.html' %}
{% block title %}
    Quiz Detail
{% endblock title %}
{% block content %}
<div class="bg-white" style="height:100vh;">

    <h1 class="special special_big no_border mx-auto">{{quiz.title}} </h1>
    <button class="btn btn-info mx-auto" style="width: 200px; display: block;"> <a class="text-decoration-none text-white" href="{% url 'quiz:home' %}">Go to Home</a> </button>
<div class="all-questions d-flex column-gap-5 flex-wrap justify-content-center">

    {% for question in quiz.question_set.all %}
    <div class="question-container mt-5">
        <h4 class="special text-bold"><b>Q{{forloop.counter}}:</b> {{question}}</h4>
        {% for option in question.option_set.all %}
        <h5 class=" mt-3 p-2   {% if option.is_correct %} bg-success-subtle
{% endif %} "> <li> {{option}}  </h5>
    {% endfor %}
</div>
{% endfor %}
</div>
</div>
{% endblock content %}

quiz/templates/quiz/edit.html
{% extends 'base.html' %}
{% block title %}
    Edit Questions
{% endblock title %}
{% block content %}
    <div class="c-container mt-3" style="display: flex; flex-direction:column; align-items: center;">
        {% for question in quiz.question_set.all %}
        <div class="custom-card card_{{question.id}} mb-3 border border-danger-subtle rounded p-3" style="width: 50%;"  hx-swap="outerHTML" hx-target="this" >
            <div class="ccard-header fs-2">
                <b> {{forloop.counter}}. {{question.name}}</b>
        
            </div>
            <div class="ccbody">
                {% for option in question.option_set.all %}
                <h5 class="ccard-title {% if option.is_correct %} bg-success text-white rounded
                    
                {% endif %} p-1  fs-4 d-flex justify-content-between">{{option}} 
                </h5>
                {% endfor %}
        
            </div>
                <a><button class="btn btn-lg btn-primary"  hx-get="{% url 'quiz:edit-question' question.id %}" >Edit</button></a>

        </div>
        {% endfor %}
    </div>
{% endblock content %}

quiz/templates/quiz/explore.html
{% extends 'base.html' %}
{% block content %}
    {% for quiz in quiz_qs %}
        <h3>{{quiz.title}}</h3>
        <h3>{{quiz.authored_on}}</h3>
        <h3>{{quiz.authored_by}}</h3>
        <h3>{{quiz.subject}}</h3>
        <button>
            <a href="{% url 'quiz:start-quiz' quiz.id %}">Start</a>
        </button>
    {% endfor %}
{% endblock content %}

quiz/templates/quiz/index.html
{% extends 'base.html' %}
{% block title %}
Quizta
{% endblock title %}
{% block content %}
<div class=" bg-white p-4"  style="height: 100vh;">
    <div class="right-pane">

        
        <div class="fs-1">
            Hello, {{request.user.first_name}}
</div>
<div class="button-container">

    
    <a class="text-decoration-none fs-4 text-white text-uppercase text-center" href="{% url 'quiz:create' %}">
                <div class=" btn btn-lg btn-success px-3 py-1 m-3 " style="width:150px">
                create
            </div>
            </a>
            
    <div>
        <ul>
            <li class="fs-5">You can create your own quizzes on the variety of subjects and share them with your friends to study or teach a particular topic.</li>
        </ul>
    </div>
</div>

<div class="button-container">

    
    <a class="text-decoration-none fs-4 text-white text-uppercase text-center"  href="{% url 'quiz:list-quiz' %}">
            <div class="btn btn-lg btn-success px-3 py-1 m-3 " style="width:150px">
                Update
            </div>
        </a>
<div>
    <ul>
        <li class="fs-5">Make change to the quizzes you recently created.</li>
    </ul>
</div>
</div>
<div class="button-container">

    
    <a class="text-decoration-none fs-4 text-white text-uppercase text-center"  href="{% url 'quiz:explore' %}">
            <div class="button-container btn btn-lg btn-success px-3 py-1 m-3 " style="width:150px">
                Explore
            </div>
            </a>
<div>
    <ul>
        <li class="fs-5">Find what others are creating and test your knowledge.
             </li>
    </ul>
</div>
</div>

<div class="button-container">


    <a class="text-decoration-none fs-4 text-white text-uppercase text-center" href="{% url 'quiz:results' %}">
        <div class="button-container btn btn-lg btn-success px-3 py-1 m-3 " style="width:150px">
            Previous Results
        </div>
    </a>
    <div>
        <ul>
            <li class="fs-5">Find what your previous results and check your progress.
            </li>
        </ul>
    </div>
</div>
</div>
</div>
{% endblock content %}

quiz/templates/quiz/question.html
{% load crispy_forms_tags %}

{{form|crispy}}

quiz/templates/quiz/quiz_info_return.html
{% load crispy_forms_tags %}
{% if saved %}
<div class="ccard-header fs-2">

    <b> {{quiz.title}}</b>
</div>
<h5 class="ccard-title fs-4">Created On: {{quiz.authored_on}}
    <h5 class="ccard-title fs-4">Public: {{quiz.is_private}} </h5>
<button class="btn btn-info" hx-get="{% url 'quiz:edit_quiz_form' quiz.id %}" hx-target="#quiz-details{{quiz.id}}"
    hx-swap="innerHTML">

    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="white" class="bi bi-pencil-fill"
        viewBox="0 0 16 16">
        <path
            d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
    </svg> <span class="fs-4 text-white">Edit</span>
</button>
{% else %}
    

<form>
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" hx-post="{% url 'quiz:edit_quiz_form' quiz.id %}" hx-target="#quiz-details{{quiz.id}}"
        hx-swap="innerHTML" class="btn btn-success"> Save</button>
</form>

    {% endif %}

quiz/templates/quiz/quiz_list.html
{% extends 'base.html' %}
{% block title %}
    All Quizzes
{% endblock title %}
{% block content %}
<div  style="display: flex;flex-wrap: nowrap;flex-direction: column;align-items: center;" >

    {% for quiz in quiz_qs %}
    <div class="custom-card m-4 border border-danger-subtle rounded p-3" style="width:40%">
        <div id="quiz-details{{quiz.id}}">
        <div class="ccard-header fs-2">

            <b> {{quiz.title}}</b>
        </div>            
        <h5 class="ccard-title fs-4">Created On: {{quiz.authored_on}} <h5 class="ccard-title fs-4">Created On: {{quiz.subject}}
            {% if not start %}
            <h5 class="ccard-title fs-4">Private: {{quiz.is_private}} </h5>
            
            <button class="btn btn-info" hx-get="{% url 'quiz:edit_quiz_form' quiz.id %}"  hx-target="#quiz-details{{quiz.id}}" hx-swap="innerHTML">
                
            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="white" class="bi bi-pencil-fill"
            viewBox="0 0 16 16">
            <path
            d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
        </svg> <span class="fs-4 text-white">Edit</span>
        </button>    
    </div>
        {% endif %}
            </h5>
            {% if start %}
            <a href="{% url 'quiz:start-quiz' quiz.id %}"><button class="btn btn-lg btn-success">Start</button></a>
            
            {% else %}
            <a href="{% url 'quiz:edit-quiz' quiz.id %}">
                
                <button class="btn btn-lg btn-primary">Edit Questions</button></a>
                {% endif %}
            </div>
            </div>
            {% endfor %}
        </div>
{% endblock content %}

quiz/templates/quiz/results.html
{% extends 'base.html' %}
{% block title %}
    Previous Results
{% endblock title %}
{% block content %}
{% regroup results by quiz as quiz_list  %}
<div class="card-container"  style="
    margin: auto;
    display: flex;
    flex-direction: column;
    align-items: center;
    ">
<div class="display-3">Results</div>

    {% for quiz in quiz_list %}
    <div class="custom-card m-4 border border-danger-subtle rounded p-3" style="width:40%">
    <div class="card">
        <div class="card-header">
            <b>{{quiz.grouper}}</b>
        </div>
        <ul class="list-group list-group-flush">
            {% for result in quiz.list %}
            
                <li class="list-group-item"><b>Scored {{result.score}}</b> on {{result.created_at}}</li>
                {% endfor %}
        </ul>
        <div class="card-footer">
            <a href="{% url 'quiz:start-quiz' quiz.grouper.id %}">

                <button class="btn text-white btn-lg btn-info">Give this quiz</button>
            </a>
            
        </div>
    </div>
</div>  
{% endfor %}
</div>
{% endblock content %}

quiz/templates/quiz/return_question.html
    <div class="custom-card mb-3 border border-danger-subtle rounded p-3" style="width: 50%;" hx-swap="outerHTML" hx-target="this" >
        <div class="ccard-header fs-2">
            <b> {{question.name}}</b>

        </div>
        <div class="ccbody">
            {% for option in question.option_set.all %}
            <h5 class="ccard-title {% if option.is_correct %} bg-success
                    
                {% endif %}   fs-4 d-flex justify-content-between">{{option}}
            </h5>
            {% endfor %}

        </div>
        <a><button class="btn btn-lg btn-primary" hx-get="{% url 'quiz:edit-question' question.id %}">Edit</button></a>

    </div>
    </div>

quiz/templates/quiz/start.html
{% extends 'base.html' %}
{% block content %}

<div class="container-c d-flex  flex-column align-items-center">
    <div class="display-2 mt-2">{{quiz.title}}</div>

    <form  method="post" style="width:50%;">
        {% csrf_token %}
        {% for question in quiz.question_set.all %}
        <div class="custom-card {% if question in correct %}
            bg-success text-white 
        {% endif %} mb-3 border border-danger-subtle rounded p-3">
            <div class="ccard-header fs-2">
                <b> {{question.name}}</b>
        
            </div>
            <div class="ccbody">
        {% for option in question.option_set.all %}
                <h5 class="ccard-title   fs-4 d-flex justify-content-between" >{{option}} {% if not given %}
                    
                    <input type="radio" name="option_{{question.id}}" id="option_" value="{{option.id}}" required> 
                {% endif %} 
            </h5>
            {% endfor %}
                
            </div>
        </div>
            {% endfor %}
           
           {% if not given %}
            
           <button class="btn btn-success" type="submit"> Submit </button>
           {% else %}
           
           <a href="{% url 'quiz:start-quiz' quiz.pk %}">

               <div class="btn btn-success" style="width: 100%;"> Try Again </div>
           </a>
           {% endif %}
            
        </form>
        <h1>Score {{score}}</h1>
        
    </div>
{% endblock content %}