core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quiz.urls")),
]

quiz/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "quiz"
urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("create/", views.create,name="create"),
    path("create/<uuid:pk>", views.create_quiz,name="create-quiz"),
    path("question/", views.new_question, name='new-question'),
    path("detail/<uuid:pk>/", views.quiz_detail,  name="quiz_detail"),
    path("list/", views.list_quiz, name='list-quiz'),
    path("explore/",views.explore, name='explore'),
    path("start/<uuid:pk>/", views.start_quiz, name="start-quiz"),
    path("edit/<uuid:pk>/", views.edit_quiz, name="edit-quiz"),
    path("edit/<int:id>/", views.edit_question, name="edit-question"),
    path("edit/quiz/<uuid:pk>/", views.edit_quiz_form, name='edit_quiz_form'),
    path("results/", views.results, name='results'),
    path("contact/", views.Contact.as_view(), name='contact'),
    path("about/", views.About.as_view(), name='about'),
    # Authentication URLs
    path(
        "login/",
        auth_views.LoginView.as_view(redirect_authenticated_user=True),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path("signup/", views.SignUp.as_view(), name="signup"),
]

quiz/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid


class User(AbstractUser):
    pass

class Subject(models.Model):
    name = models.CharField(max_length=200)
    sub_code = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name",)
        verbose_name = "Subject"
        verbose_name_plural = "Subjects"


class Quiz(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200 ,blank=True, null=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    authored_on = models.DateTimeField(auto_now=True)
    authored_by = models.ForeignKey(User, on_delete=models.CASCADE)
    is_private = models.BooleanField(default=False)

    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ("-authored_on",)
        verbose_name = "Quiz"
        verbose_name_plural = "Quizzes"


class Question(models.Model):
    name = models.CharField(max_length=800)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Question"
        verbose_name_plural = "Questions"


class Option(models.Model):
    name = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Option"
        verbose_name_plural = "Options"

class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    by = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.PositiveIntegerField()
    created_at = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = 'Result'
        verbose_name_plural = 'Results'
    

quiz/forms.py
from django import forms
from .models import User, Quiz
from django.contrib.auth.forms import UserCreationForm


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "username",
            "password1",
            "password2",
        )

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in ["username", "password1", "password2"]:
            self.fields[field].help_text = None
            self.fields['first_name'].label = 'Name'
            self.fields['first_name'].required = True

class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        exclude = ['authored_by',]
    def __init__(self, *args, **kwargs):
        super(QuizForm, self).__init__(*args, **kwargs)
        self.fields['title'].label = ''
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'special special_big', 'placeholder':'Quiz Title'}))


class QuestionForm(forms.Form):
    quiz = forms.UUIDField(widget=forms.HiddenInput())
    question = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'special', 'placeholder':'Question'}))
    option_1 = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'special special_small', 'placeholder':'Option A'}))
    option_2 = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'special special_small', 'placeholder':'Option B'}))
    option_3 = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'special special_small', 'placeholder':'Option C'}))
    correct_answer = forms.ChoiceField(choices=[(1, 'A'), (2, 'B'), (3, 'C')], widget=forms.RadioSelect(attrs={'class':'radio-inline', 'required':True}))

    

quiz/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, CreateView
from django.contrib.auth import get_user_model
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import UserForm, QuizForm, QuestionForm
from .models import User, Subject, Quiz, Question, Option, Result
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

class Home(LoginRequiredMixin, TemplateView):
    template_name = "quiz/index.html"

class Contact(TemplateView):
    template_name = "quiz/contact.html"

class About(TemplateView):
    template_name = "quiz/aboutus.html"


class SignUp(CreateView):
    model = get_user_model
    form_class = UserForm
    success_url = "/"
    template_name = "registration/signup.html"

    def form_valid(self, form):
        user = form.save(commit=False)
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password1"]
        new_user = authenticate(self.request, username=username, password=password)
        user.save()
        if new_user is not None:
            login(self.request, user=new_user)

        return super().form_valid(form)

@login_required()
def create(request):
    subjects = Subject.objects.all().values_list('name')
    form = QuizForm()
    question_form= None
    disabled = False
    if request.method == "POST":
        form = QuizForm(request.POST)
        if form.is_valid():
            quiz = form.save(commit=False)
            quiz.authored_by = request.user
            quiz.save()
            return redirect(reverse('quiz:create-quiz', kwargs={'pk':quiz.id}))
    return render(request, "quiz/create.html", {'subjects':subjects, 'disabled':disabled, 'form':form, 'question_form':question_form})

@login_required()
def create_quiz(request, pk):
    form = QuestionForm(initial={'quiz':pk})
    return render(request, 'quiz/create_questions.html', {'form':form})

def new_question(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            question = Question.objects.create(quiz_id=cd['quiz'], name=cd['question'])
            for i in [1,2,3]:
                option = Option.objects.create(name=cd[f'option_{i}'], is_correct=(i==int(cd['correct_answer'])), question=question)

            form = QuestionForm(initial={'quiz':cd['quiz']})
    
    return render(request, 'quiz/question.html', {'form':form})

@login_required()
def quiz_detail(request, pk):
    quiz = Quiz.objects.get(id=pk)
    return render(request, 'quiz/detail.html', {'quiz':quiz})

@login_required()
def list_quiz(request):
    quiz_qs = Quiz.objects.filter(authored_by=request.user)
    return render(request, 'quiz/quiz_list.html', {'quiz_qs':quiz_qs})

@login_required()
def explore(request):
    quiz_qs = Quiz.objects.exclude(authored_by=request.user).exclude(is_private=True)
    return render(request, 'quiz/quiz_list.html', {'quiz_qs':quiz_qs, 'start':True})

@login_required()
def start_quiz(request, pk):
    quiz = Quiz.objects.get(id=pk)
    count = 0
    correct = []
    given = False
    if request.method == 'POST':
        questions = quiz.question_set.all()
        for question in questions:
            option = question.option_set.all().get(is_correct=True)
            if option.id == int(request.POST.get(f'option_{question.id}')):
                count+=1
                correct.append(question)
        result = Result.objects.create(by=request.user, quiz=quiz, score=count)
        given = True
    return render(request, "quiz/start.html", {'quiz':quiz, 'score':count, 'given':given, 'correct':correct})

@login_required()
def edit_quiz(request, pk):
    quiz = Quiz.objects.get(id=pk)

    return render(request, 'quiz/edit.html', {'quiz':quiz})


@login_required()
def edit_question(request, id):
    question = Question.objects.get(id=id)
    options = question.option_set.all()
    correct = [all(i) for i in (options.values_list('is_correct'))].index(True) +1
    form = QuestionForm(initial={'quiz': question.quiz, 'question':question.name, 'option_1': options[0].name, 'option_2':options[1].name, 'option_3':options[2].name,'correct_answer':correct})
    if request.method == "POST":
        form = QuestionForm(request.POST)
        print(form.errors)
        if form.is_valid():
            cd = form.cleaned_data
            question.name = cd['question']
            question.save()
            for i,option in enumerate(options, 1):
                option.name, option.is_correct =cd[f'option_{i}'],False
                if int(cd['correct_answer']) == i: option.is_correct=True
                option.save()
            return render(request, 'quiz/return_question.html', {'question':question})
   
    return render(request, "quiz/question_form.html", {'form':form, 'id':id})

@login_required()
def edit_quiz_form(request, pk):
    quiz = Quiz.objects.get(id=pk)
    form = QuizForm(instance=quiz)
    saved = False
    if request.method == "POST":
        form = QuizForm(request.POST, instance=quiz)
        form.save()
        saved = True
    return render(request, 'quiz/quiz_info_return.html', {'form':form,'quiz':quiz, 'saved':saved})

@login_required()
def results(request):
    results_qs = Result.objects.all().filter(by=request.user).order_by('quiz')
    return render(request, 'quiz/results.html', {'results': results_qs})

quiz/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="{% static 'htmx.min.js' %}"></script>
    <title>{% block title %}

        {% endblock title %}</title>
</head>

<body>
    {% include 'nav.html' %}
    {% block content %}

    {% endblock content %}
</body>

{% comment %}
<footer class="fs-5 fixed-bottom text-center p-3 fw-bold container-fluid" style="background-color: #ff8142ab;">
    Made by Vivek! Trust Me
</footer>
{% endcomment %}
</html>

quiz/templates/nav.html
{% load static %}
{% if request.user.is_authenticated %}
<nav class="navbar" style="background-color:#f2edd9">
    <div class="container-fluid ">
        <a class="navbar-brand column-gap-3 d-flex align-items-center" href="/">
            <img src="{% static 'images/logo.png' %}" alt="Logo" width="64"
                class="d-inline-block align-text-top">
                <span class="nav_text"> Quizter</span>
            </a>
        <span class="navbar-brand mb-0 h1 text-center"  style="display: flex;gap: 2em;">
           
            <a href="{% url 'quiz:logout' %}">

                <svg xmlns="http://www.w3.org/2000/svg" width="42" height="42" fill="#ff8042" class="bi bi-door-open-fill"
                viewBox="0 0 16 16">
                <path
                d="M1.5 15a.5.5 0 0 0 0 1h13a.5.5 0 0 0 0-1H13V2.5A1.5 1.5 0 0 0 11.5 1H11V.5a.5.5 0 0 0-.57-.495l-7 1A.5.5 0 0 0 3 1.5V15H1.5zM11 2h.5a.5.5 0 0 1 .5.5V15h-1V2zm-2.5 8c-.276 0-.5-.448-.5-1s.224-1 .5-1 .5.448.5 1-.224 1-.5 1z" />
            </svg>
            <div class="name text-muted text-decoration-none text-center pt-1">Log Out</div>        
        </a>
            <a href="{% url 'quiz:contact' %}">
            
                <svg xmlns="http://www.w3.org/2000/svg" width="42" height="42" fill="#ff8042" class="bi bi-envelope-check-fill"
                    viewBox="0 0 16 16">
                    <path
                        d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555ZM0 4.697v7.104l5.803-3.558L0 4.697ZM6.761 8.83l-6.57 4.026A2 2 0 0 0 2 14h6.256A4.493 4.493 0 0 1 8 12.5a4.49 4.49 0 0 1 1.606-3.446l-.367-.225L8 9.586l-1.239-.757ZM16 4.697v4.974A4.491 4.491 0 0 0 12.5 8a4.49 4.49 0 0 0-1.965.45l-.338-.207L16 4.697Z" />
                    <path
                        d="M16 12.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0Zm-1.993-1.679a.5.5 0 0 0-.686.172l-1.17 1.95-.547-.547a.5.5 0 0 0-.708.708l.774.773a.75.75 0 0 0 1.174-.144l1.335-2.226a.5.5 0 0 0-.172-.686Z" />
                </svg>
                <div class="name text-muted text-decoration-none text-center pt-1">Contact Us</div>
            </a>
            </a>
            <a href="{% url 'quiz:about' %}">
            
                <svg xmlns="http://www.w3.org/2000/svg" width="42" height="42" fill="#ff8042" class="bi bi-book-half"
                    viewBox="0 0 16 16">
                    <path
                        d="M8.5 2.687c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z" />
                </svg>
                <div class="name text-muted text-decoration-none text-center pt-1">About Us</div>
            </a>
        </span>
        

    </div>
</nav>
{% else %}
    <nav class="navbar ">
        <div class="container-fluid align-right justify-content-end">
           
            <span class="navbar-brand mb-0 h1 text-center"  style="display: flex;gap: 2em;">
                {% if request.path == '/signup/'%}
                <a href="{% url 'quiz:login' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="42" height="42" fill="#ff8042" class="bi bi-arrow-left-square-fill"
                        viewBox="0 0 16 16">
                        <path
                            d="M16 14a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12zm-4.5-6.5H5.707l2.147-2.146a.5.5 0 1 0-.708-.708l-3 3a.5.5 0 0 0 0 .708l3 3a.5.5 0 0 0 .708-.708L5.707 8.5H11.5a.5.5 0 0 0 0-1z" />
                    </svg>
                    <div class="name text-muted text-decoration-none text-center px-3 py-1">Log In</div>
                </a>
                {% else %}
                    
                <a href="{% url 'quiz:signup' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="42" height="42" fill="#ff8042" class="bi bi-plus-square-fill"
                    viewBox="0 0 16 16">
                    <path
                        d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0z" />
                </svg>
                <div class="name text-muted text-decoration-none text-center px-3 py-1">Sign Up</div>
                </a>
                {% endif %}
                <a href="{% url 'quiz:contact' %}">
                
                    <svg xmlns="http://www.w3.org/2000/svg" width="42" height="42" fill="#ff8042" class="bi bi-envelope-check-fill"
                        viewBox="0 0 16 16">
                        <path
                            d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555ZM0 4.697v7.104l5.803-3.558L0 4.697ZM6.761 8.83l-6.57 4.026A2 2 0 0 0 2 14h6.256A4.493 4.493 0 0 1 8 12.5a4.49 4.49 0 0 1 1.606-3.446l-.367-.225L8 9.586l-1.239-.757ZM16 4.697v4.974A4.491 4.491 0 0 0 12.5 8a4.49 4.49 0 0 0-1.965.45l-.338-.207L16 4.697Z" />
                        <path
                            d="M16 12.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0Zm-1.993-1.679a.5.5 0 0 0-.686.172l-1.17 1.95-.547-.547a.5.5 0 0 0-.708.708l.774.773a.75.75 0 0 0 1.174-.144l1.335-2.226a.5.5 0 0 0-.172-.686Z" />
                    </svg>
                    <div class="name text-muted text-decoration-none text-center pt-1">Contact Us</div>
                </a>
                </a>
                <a href="{% url 'quiz:about' %}">
                
                    <svg xmlns="http://www.w3.org/2000/svg" width="42" height="42" fill="#ff8042" class="bi bi-book-half"
                        viewBox="0 0 16 16">
                        <path
                            d="M8.5 2.687c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z" />
                    </svg>
                    <div class="name text-muted text-decoration-none text-center pt-1">About Us</div>
                </a>
            </span>
    
        </div>
    </nav>
{% endif %}